### PR TITLE
Fixes undefined properties error in tests (closes issue #425)

### PR DESCRIPTION
**Pull request by klougod**

### CODE REVIEW

**Comment by klougod** [comment]
@dilanx Hello,

Here is the PR as requested in issue #425, hope it is fine to merge, if there's any update or changes just comment and I'll correct it immediately.

Thanks

**Comment by dilanx** [comment]
Sorry about the delay, @klougod.

Is this update specifically for versions prior to craco 7? Are you able to recreate your original issue on the alpha version of craco?

Because CRA 4 (craco 6) is over a year old now, it may be best to stop supporting it in favor of CRA 5 (craco 7). Many packages only support CRA 5 now anyways. I wouldn't want to merge your PR if it'll just be overwritten soon by the new update.

If the intent is that this is just for craco 6 (which will soon stop being supported), I can go ahead and merge and release a new craco 6 version.

**Comment by klougod** [comment]
> Sorry about the delay, @klougod.
> 
> Is this update specifically for versions prior to craco 7? Are you able to recreate your original issue on the alpha version of craco?
> 
> Because CRA 4 (craco 6) is over a year old now, it may be best to stop supporting it in favor of CRA 5 (craco 7). Many packages only support CRA 5 now anyways. I wouldn't want to merge your PR if it'll just be overwritten soon by the new update.
> 
> If the intent is that this is just for craco 6 (which will soon stop being supported), I can go ahead and merge and release a new craco 6 version.

I'm having this problem with craco 6 but i'll surely try to reproduce it with craco 7, soon i'll give an update here

**Comment by klougod** [comment]
@dilanx Hi,

As I expected this only happens in craco version 6, the intent for this PR would be to fix it only for the version 6, in my case and many others it would help since I cant fully update to craco 7.

Thanks

**Comment by dilanx** [comment]
Okay sounds good, I'll merge your changes and release a patch for version 6.

**Review by dilanx — APPROVED** [review]

**Pull request merged**
